#Removes the pull-request label then adds the pr-approved label
on: pull_request_review
name: Label approved pull requests
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "pr-approved"
        REMOVE_LABEL: "pull-request"

    - name: Slack Notification Pull Request Approved
      uses: rtCamp/action-slack-notify@v2.3.0
      env:
        SLACK_CHANNEL: trash-tracker
        SLACK_COLOR: ${{ job.status }} 
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Pull Request Approved'
        SLACK_TITLE: PR Approved
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
