#On creation of a new pull request add the label pull-request

name: Add Labels

on:
  pull_request:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        
        with:
          labels: pull-request

      - name: Slack Notification Pull Request Created
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_CHANNEL: trash-tracker
          SLACK_COLOR: ${{ job.status }} 
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Pull Request Created'
          SLACK_TITLE: PR Created
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

